### DISCUSSION TITLE
Thoughts on clang-format migration

### DISCUSSION THREAD

**Discussion by scarf005** [cataclysmbn/Cataclysm-BN#2012] [General]
## Reasoning
- astyle is outdated
- does not support c++20 language features (spaceship operator <=> is split into <= >)
- does not work consistently on new C++ features (such as: control statement inside lambda)

## Pros

- Easier to integrate (default in many C++ extensions)
- Consistent behavior

## Cons
- Some styles may be impossible to port over
- Large portion of code may be needed to be formatted
- Needs to change every workflow
- Porting from DDA would be a nightmare

## Conclusion
- The cost for migration outweighs benefits.
- Halted until at least 99% of features can be ported over

## Example
```yaml
BasedOnStyle: Google

# One True Brace Style
BreakBeforeBraces: Custom
BraceWrapping:
    AfterClass: true
    AfterControlStatement: Never
    AfterNamespace: true
    AfterStruct: true
    AfterUnion: true
    AfterFunction: true
    AfterExternBlock: true
    BeforeCatch: true
    BeforeElse: true
    IndentBraces: false

IndentWidth: 4
SortIncludes: Never

# maximum length for a single unbroken line
ColumnLimit: 100

SpaceAfterTemplateKeyword: false

AllowShortFunctionsOnASingleLine: None

IndentAccessModifiers: true

UseTab: Never

SpacesInParentheses: true
SpacesInSquareBrackets: true
SpaceBeforeParens: Never
SpacesBeforeTrailingComments: 1
```
